---
- hosts: localhost
  become: no
  connection: local

  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  #vars_files:
  #  - vars/{{ config_files }}.yml

  tasks:
    # Removing as not currently in use:
    #- name: Get size of long to determine architecture
    #  command: getconf LONG_BIT
    #  register: long_bit
    #  changed_when: false

    # Removing as not currently used:
    #- name: Get list of installed packages
    #  command: pacman -Qq
    #  register: installed_packages
    #  changed_when: false


    # Removing as updates should probably be done manually
    #- include: tasks/update-manjaro.yml

    # Basic configuration:
    - include: tasks/basic-configuration.yml
    - include: tasks/alsamixer-automute.yml
    - include: tasks/num-lock.yml

    # Install software:
    - include: tasks/google-chrome.yml
    - include: tasks/nvpy.yml
    # Despotify seems to be usless!!
    #- include: tasks/despotify.yml

  handlers:
    - name: reload i3
      shell: i3-msg reload

    - name: save alsamixer
      become: yes
      shell: alsactl store

    - name: set xorg
      shell: mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf
      become: yes

    - name: monitor setup
      script: files/3-monitor-setup.sh

    - debug: msg="set xorg has been run!"
