---
- hosts: localhost
  become: no
  connection: local
  gather_facts: no

  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  vars_files:
    - vars/home-pc.yml
    #- vars/{{ config_files }}.yml

  tasks:
    #######################
    # Basic configuration #
    #######################
    - include: tasks/xorg.yml
    - include: tasks/conky.yml
    - include: tasks/disable-automute.yml
    - include: tasks/enable-numlock.yml
    - include: tasks/fonts-terminal.yml
    - include: tasks/fonts-desktop.yml

    - include: tasks/vim.yml user={{ user_item }}
      with_items: '{{ users_inc_super }}'
      loop_control:
        loop_var: user_item

    ########################
    #       SOFTWARE       #
    ########################

    # Internet
    # --------

    - include: tasks/google-chrome.yml

    # Collaboration
    # -------------

    - include: tasks/nvpy.yml

  handlers:
    - name: reload i3
      shell: i3-msg reload

    - name: save alsamixer
      become: yes
      shell: alsactl store

    - name: set xorg
      shell: mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf
      become: yes

    - name: monitor setup
      script: files/3-monitor-setup.sh

    - debug: msg="set xorg has been run!"

    - name: enable numlockx
      shell: numlockx
      become: no
