---
- hosts: localhost
  become: no
  connection: local
  gather_facts: no

  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  vars_files:
    - vars/all.yml
    - vars/home-pc.yml
    #- vars/{{ config_files }}.yml

  handlers:
    - include: handlers/handlers.yml

  tasks:
    #######################
    # Basic configuration #
    #######################
    - include: tasks/xorg.yml
    - include: tasks/conky.yml
    - include: tasks/disable-automute.yml
    - include: tasks/enable-numlock.yml
    - include: tasks/fonts-terminal.yml
    - include: tasks/fonts-desktop.yml
    - include: tasks/oracle-java.yml
    - include: tasks/dnsutils.yml
    - include: tasks/nmap.yml

    - include: tasks/vim.yml user={{ user_item }}
      with_items: '{{ users_inc_super }}'
      loop_control:
        loop_var: user_item

    ########################
    #       SOFTWARE       #
    ########################

    # Internet
    # --------
    - include: tasks/google-chrome.yml
    - include: tasks/firefox.yml
    # telegram-desktop | telegram-desktop-bin
    - include: tasks/telegram-desktop-bin.yml
    - include: tasks/slack-desktop.yml
    - include: tasks/transmission.yml
    - include: tasks/pidgin.yml
    - include: tasks/filezilla.yml
    # Broken in the AUR (PGP sig errors)
    #- include: tasks/tor-browser.yml
    - include: tasks/qtox.yml

    # Collaboration
    # -------------
    - include: tasks/nvpy.yml

    # Sound & Video
    # -------------
    - include: tasks/mplayer.yml
    - include: tasks/clementine.yml
    - include: tasks/cmus.yml
    - include: tasks/spotify.yml

    # Office
    # ------
    - include: tasks/libreoffice.yml
    - include: tasks/gnucash.yml
    - include: tasks/freemind.yml
    - include: tasks/workrave.yml

    # Programming
    # -----------
    - include: tasks/netbeans.yml
    - include: tasks/geany.yml
    - include: tasks/mariadb.yml
    - include: tasks/mysql-workbench.yml
    
    # Rackspace Cloud Tools
    # ---------------------
    # https://aur.archlinux.org/packages/supernova/
    - include: tasks/supernova.yml
    # 
    # Virtualisation
    # --------------
    - include: tasks/qemu.yml

