---
- hosts: localhost
  become: no
  connection: local
  gather_facts: no

  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  vars_files:
      #- vars/{{ config_files }}.yml
    - vars/home-pc.yml

  tasks:
    # Basic configuration:
    - include: tasks/basic-configuration.yml
    - include: tasks/alsamixer-automute.yml
    - include: tasks/num-lock.yml

    # Install software:
    - include: tasks/google-chrome.yml
    - include: tasks/nvpy.yml

      # Configure VIM with Ultimate vimrc
    - include: tasks/vim.yml user={{ user_item }}
      with_items: '{{ users_inc_super }}'
      loop_control:
        loop_var: user_item

  handlers:
    - name: reload i3
      shell: i3-msg reload

    - name: save alsamixer
      become: yes
      shell: alsactl store

    - name: set xorg
      shell: mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf
      become: yes

    - name: monitor setup
      script: files/3-monitor-setup.sh

    - debug: msg="set xorg has been run!"

    - name: enable numlockx
      shell: numlockx
      become: no
