---
#- hosts: all
  #name: Configure Xorg for three monitor setup
  #become: yes
  #hosts: localhost
  
  #- tasks:
- name: Copy XOrg configuration file (nvidia.conf) 
  copy:
    src=files/nvidia.conf
    dest=/etc/X11/mhwd.d/nvidia.conf
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
    backup=yes

- name: Register XOrg configuration file with NVidia
  #become: yes
  shell: mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf

- name: Create screenLayout Directory
  file: path=~/.screenLayout state=directory owner=andy group=users mode=755

- name: Copy xrandr configuration file
  copy: src=files/three-monitor-config.sh dest=~/.screenLayout/three-monitor-config.sh owner=andy group=users mode=755

- name: Execute XRandR script to make changes without requiring a reboot
  script: files/three-monitor-config.sh

