---
- name: Copy XOrg configuration file (nvidia.conf)
  become: yes
  copy:
    src=files/nvidia.conf
    dest=/etc/X11/mhwd.d/nvidia.conf
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
    backup=yes

- name: Register XOrg configuration file with NVidia
  become: yes
  shell: mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf

- name: Create screenLayout Directory
  file: path=~/.screenLayout state=directory owner=andy group=users mode=755

- name: Copy xrandr configuration file
  copy: src=files/three-monitor-config.sh dest=~/.screenLayout/three-monitor-config.sh owner=andy group=users mode=755

- name: Execute XRandR script to make changes without requiring a reboot
  script: files/three-monitor-config.sh

- name: Change i3 tray output to primary monitor
  lineinfile:
    dest: "~/.i3/config"
    regexp: "tray_output primary"
    line: "     tray_output primary"
    state: present

- name: Configure Conky X coordinates
  become: yes
  lineinfile:
    dest: "/usr/share/conky/conky1.10_shortcuts_maia"
    regexp: "gap_x"
    line: "        gap_x = 2280"
    state: present


- name: Configure Conky Y coordinates
  become: yes
  lineinfile:
    dest: "/usr/share/conky/conky1.10_shortcuts_maia"
    regexp: "gap_y"
    line: "        gap_y = 55"
    state: present

