---
- name: Copy xorg configuration file (nvidia.conf)
  become: yes
  copy:
    src=files/nvidia.conf
    dest=/etc/X11/mhwd.d/nvidia.conf
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
    backup=yes
  notify: set xorg

  #- name: Register XOrg configuration file with NVidia
  #become: yes
  #shell: mhwd-gpu --setgl nvidia --setxorg /etc/X11/mhwd.d/nvidia.conf

- name: Create screenLayout Directory
  file: path=~/.screenLayout state=directory owner=andy group=users mode=755

- name: Copy xrandr configuration file
  copy: src=files/3-monitor-setup.sh dest=~/.screenLayout/3-monitor-setup.sh owner=andy group=users mode=755
  notify: monitor setup

  #- name: Execute XRandR script to make changes without requiring a reboot
  #script: files/3-monitor-setup.sh

- name: Change i3 tray output to primary monitor
  lineinfile:
    dest: "~/.i3/config"
    regexp: "tray_output primary"
    line: "     tray_output primary"
    state: present

- name: Configure Conky - Help menu position
  become: yes
  lineinfile:
    dest: "/usr/share/conky/conky1.10_shortcuts_maia"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "gap_x"
      line: "        gap_x = 2280,"
    - regexp: "gap_y"
      line: "        gap_y = 50,"
  
  #  lineinfile:
  #  dest: "/usr/share/conky/conky1.10_shortcuts_maia"
  #  regexp: "gap_y"
  #  line: "        gap_y = 50,"
  #  state: present

- name: Configure Conky - System performance position
  become: yes
  lineinfile:
    dest: "/usr/share/conky/conky_maia"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }} "
    state: present
  with_items:
    - regexp: "gap_x"
      line: "        gap_x = 30,"
    - regexp: "gap_y"
      line: "        gap_y = 130,"



  #lineinfile:
  #  dest: "/usr/share/conky/conky_maia"
  #  regexp: "gap_y"
  #  line: "        gap_y = 130,"
  #  state: present



  #- name: Configure Conky - Help Position (Y coordinate)
  #  become: yes
  #  lineinfile:
  #    dest: "/usr/share/conky/conky1.10_shortcuts_maia"
  #    regexp: "gap_y"
  #    line: "        gap_y = 55,"
  #    state: present

  #- name: Configure Conky - System Information Position (X coordinate)
  #become: yes
  #lineinfile:
  #  dest: "/usr/share/conky/conky_maia"
  #  regexp: "gap_x"
  #  line: "        gap_x = 30,"
  #  state: present

  #- name: Configure Conky - System Information Position (Y coordinate)
  #become: yes
  #lineinfile:
  #  dest: "/usr/share/conky/conky_maia"
  #  regexp: "gap_y"
  #  line: "        gap_y = 130,"
  #  state: present

