---

- name: Install recommended Adobe fonts
  yaourt: name={{ item }} state="present"
  with_items:
    - ttf-droid
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
  become: yes
  become_user: "{{ primary_non_root_user }}"
