---

- name: Clone ultimate vimrc repo for {{ user }}
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/amix/vimrc.git
    dest: ~{{ user }}/.vim_runtime

- name: Install Awesome version of ultimate vimrc for {{ user }}
  shell: sh ~{{ user }}/.vim_runtime/install_awesome_vimrc.sh 
  become_user: "{{ user }}"


